version: "3.7"
services:

  mongo:
    image: mongo:4.4
    networks:
      - acheronet
    restart: unless-stopped

  caronte:
    image: ghcr.io/eciavatta/caronte:latest
    build: .
    ports:
      - "3333:3333"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    networks:
      - acheronet
    restart: unless-stopped

networks:
  acheronet:
